apiVersion: 3

dataDisplay:
  exampleSection: 1En__Ethiopic 1:1
  exampleSectionHtml: <code>1En__Ethiopic 1:1</code>
  textFormat: text-orig-full

docs:
  docBase: https://github.com/alexsosn/Pseudepigrapha-TF/blob/main/docs
  docExt: .md
  docPage: tf-app

provenanceSpec:
  corpus: Online Critical Pseudepigrapha (Text-Fabric conversion)
  version: "0.1"

typeDisplay:
  book:
    features: version_title version_kind language
