from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_exact(path: Path, old: str, new: str, expected: int, label: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != expected:
        raise RuntimeError(f"{label}: expected {expected} matches, found {count}")
    path.write_text(text.replace(old, new), encoding="utf-8")


audit = ROOT / "src" / "pseudepigrapha_tf" / "audit.py"
replace_exact(
    audit,
    '''from .source_versions import (\n    GENERATED_TRANSLATION_MARKER,\n    GeneratedTranslationClassificationError,\n    is_generated_translation_version,\n    is_wrapped_legacy_version,\n)\n''',
    '''from .source_versions import GENERATED_TRANSLATION_MARKER, is_wrapped_legacy_version\n''',
    1,
    "shared generated classifier imports",
)
replace_exact(
    audit,
    '''def _raw_translation_unit_identities(\n''',
    '''def _audit_is_generated_translation_version(version: ET.Element) -> bool:\n    """Independently classify the strict source-declared OCP-Trans structure.\n\n    This deliberately does not call the parser's classifier: semantic parity must\n    be able to catch a regression in that implementation rather than echo it.\n    """\n\n    manuscripts = list(version.findall("manuscripts/ms"))\n    manuscript_abbrevs = [ms.get("abbrev", "") for ms in manuscripts]\n    readings = list(version.iter("reading"))\n    reading_witnesses = [tuple(reading.get("mss", "").split()) for reading in readings]\n\n    marker_in_manuscripts = GENERATED_TRANSLATION_MARKER in manuscript_abbrevs\n    marker_in_readings = any(\n        GENERATED_TRANSLATION_MARKER in witnesses for witnesses in reading_witnesses\n    )\n    if not marker_in_manuscripts and not marker_in_readings:\n        return False\n\n    title = version.get("title", "")\n    context = f"version {title!r}" if title else "version"\n    if manuscript_abbrevs != [GENERATED_TRANSLATION_MARKER]:\n        raise ValueError(\n            f"{context}: OCP-Trans generated translation marker is mixed with other manuscripts"\n        )\n    if not readings:\n        raise ValueError(\n            f"{context}: OCP-Trans generated translation marker has no readings"\n        )\n    if any(witnesses != (GENERATED_TRANSLATION_MARKER,) for witnesses in reading_witnesses):\n        raise ValueError(\n            f"{context}: OCP-Trans generated translation marker is mixed with other reading witnesses"\n        )\n    return True\n\n\ndef _raw_translation_unit_identities(\n''',
    1,
    "independent audit classifier insertion",
)
replace_exact(
    audit,
    '''                try:\n                    generated = is_generated_translation_version(version)\n                except GeneratedTranslationClassificationError as exc:\n                    raise InvalidSourceError(f"{path.name}: {exc}") from exc\n''',
    '''                try:\n                    generated = _audit_is_generated_translation_version(version)\n                except ValueError as exc:\n                    raise InvalidSourceError(f"{path.name}: {exc}") from exc\n''',
    1,
    "raw audit classifier call",
)

readme = ROOT / "README.md"
old = '''The refreshed OCP snapshot also contains English and French versions generated by OCP's translation workflow. Until those versions receive first-class provenance/alignment semantics in Pseudepigrapha-TF, the converter intentionally excludes only versions carrying the structurally consistent upstream `OCP-Trans` provenance marker. It does **not** classify translations by language or title. Mixed or ambiguous use of `OCP-Trans` fails loudly, and `conversion-report.json` records every intentionally excluded version. Full-file SHA-256 provenance still covers the unmodified upstream XML bytes, including excluded generated versions.\n'''
new = '''The refreshed OCP snapshot also contains English and French versions generated by OCP's translation workflow. Pseudepigrapha-TF preserves them as a first-class **generated-translation layer**, classified only by the strict source-declared `OCP-Trans` structure — never by language or title. This distinction is important because the pinned `4Q548` has a genuine scholarly English source version. Generated books and units carry `version_kind=generated_translation`, generated books link to their exact source version through `translation_of`, and generated units link occurrence-by-occurrence through `translation_unit_of`. The synthetic `OCP-Trans` manuscript remains available as provenance (`synthetic_witness=1`) but is excluded from historical witness/apparatus semantics. Mixed or ambiguous marker use fails loudly.\n\nThe exact pinned snapshot records its generation workflow as `llm` with model `openrouter/google/gemini-3.7-flash`; those history-derived claims are emitted only when the conversion is tied to that evidenced upstream commit. An arbitrary later snapshot with the same structural marker remains identifiable as generated but is not assigned an unevidenced model. Generated-capable TF datasets declare `generatedTranslationLayer=1` in corpus metadata so `Apparatus` can fail closed if a selective load omits provenance features; source-only corpora retain the previous partial-load behavior.\n\n### Generated translations\n\nUse `Translations` for parallel generated text and `Apparatus` for source/critical textual evidence:\n\n```python\nfrom tf.fabric import Fabric\nfrom pseudepigrapha_tf import Apparatus, Translations\n\nTF = Fabric(locations=["tf/0.1"], modules=[""], silent="deep")\napi = TF.load(\n    "book ocp_book version_title version_kind language generated_language "\n    "generation_marker generation_method generation_model unit_id source_ref "\n    "reading_text is_primary synthetic_witness undefined_manuscript ms_abbrev "\n    "translation_of translation_unit_of reading_of manuscript_of witness",\n    silent="deep",\n)\n\nT = Translations(api)\ntranslations = T.versions(work="4Ezra", language="French")\ngenerated_book = translations[0]["node"]\nT.aligned_units(generated_book)\nT.passage(translations[0]["id"], "1", "1")\n\nA = Apparatus(api)\n# Source/critical witnesses only: OCP-Trans is synthetic provenance, not evidence.\nA.work_passage("4Ezra", "1", "1")\n```\n\nAlignment uses full source division path + stripped unit id + occurrence ordinal, not positional zip or bare id. This preserves duplicate upstream identities and the known reordered generated versions without inventing correspondence. `conversion-report.json` independently rereads raw XML and reports generated version/unit counts, alignment coverage, provenance, and mapping diagnostics.\n'''
replace_exact(readme, old, new, 1, "README generated translation section")
